- Dockerfile.rhel
We need to set `io.openshift.release.operator true` label for all images that go in release
> Label aws provider image

- pkg/actuators/machine/actuator_test.go
- pkg/actuators/machine/controller_test.go
- pkg/actuators/machine/machine_scope.go
- pkg/actuators/machine/reconciler.go
- pkg/actuators/machine/reconciler_test.go
- pkg/actuators/machine/stubs.go
- pkg/actuators/machine/suite_test.go
We are seeing instances where AWS is not returning the instance we just created within a second or two of the initial creation time, returning a 400 error saying that the instance does not exist.
This makes the machine go into failed right now, and, in conjunction with an MHC, can lead to leaked machines as the instances are deleted before AWS acknowledges the existence of the Machine.
This PR is an attempt to improve this experience.
It does:
1. Do not set the addresses after create - this prevents the machine controller from saying the instance is provisioned, if exists does not return the instance, it will call create again
2. Before we create, we attempt exists again by looking for existing instances - if this succeeds, requeue and the next reconcile should work and call Update which …
> Bug 2025767: Prevent Machine from being considered provisioned until it exists in AWS

- pkg/actuators/machine/instances.go
AWS documentation suggests that `IO1`, `IO2` and `GP3` block devices all support a configurable IOPS setting. We are only allowing this for `IO1` right now, so we should make sure that we set the IOPS on other supported types as well.
> The following are the supported values for each volume type:
> - gp3 : 3,000-16,000 IOPS
> - io1 : 100-64,000 IOPS
> - io2 : 100-64,000 IOPS
> Bug 2040504: Ensure IOPS setting is honoured on all supported block device types

- pkg/actuators/machine/instances_test.go
- pkg/actuators/machine/reconciler.go
- pkg/actuators/machine/utils.go
**issue :**
Currently the user-defined tags during install are passed directly as parameters of the Machine and Machineset resources for the master and worker. As a result these tags cannot be updated by consulting the Infrastructure resource of the cluster where the user defined tags are written.
so intention of the changes is to update EC2 instance,
**Solution :** 
The machine-api-provider-aws  update the EC2 instance tags from infrastructure resource on periodical bases.  when the resource tags are updated it should update the tags on the EC2 instances without restarts.
**target Release :** 4.11
> CFE-68 : user defined resource tags on EC2 instances updatable

- pkg/actuators/machine/instances_test.go
- pkg/actuators/machine/reconciler.go
- pkg/actuators/machine/utils.go
#15 introduced a change to ensure tags are updated post Machine creation. However, it didn't account for the tags in the Machine spec as we do on create, as such, any tags set on the Machine themselves were removed on first update and discarded.
This resolves the issue so now the tags from the Machine spec are included as they were before
> Ensure Machine level tags have precedence over infrastructure level tags

- pkg/actuators/machine/reconciler.go
- pkg/actuators/machine/reconciler_test.go
- pkg/actuators/machine/stubs.go
Currently, if we fail to deregister the NLB target, we might leak the instance because we terminate the instance before the NLB target is deregistered.
We should not be removing the machine until the NLB targets have been deregistered.
Turns out there were no tests for delete, so I've added some so that we can test this.
> Bug 2065160: Ensure IP based NLB targets are deregistered before Machines are removed

- pkg/actuators/machine/machine_scope.go
- pkg/actuators/machine/machine_scope_test.go
- pkg/actuators/machine/utils.go
- pkg/actuators/machine/utils_test.go
This PR fixes a bug reported at https://bugzilla.redhat.com/show_bug.cgi?id=2072195 where adding an empty domain-name in a Custom DHCP Option Set wrongfully ends up breaking the CSR validation for nodes created afterwards.
We know that if a DHCP Options Set does not contain a `domain-name` key, then the metadata service, used by the legacy cloud provider to populate Node.Addresses and therefore the CSR, will not contain a domain. We need Machine.Addresses to contain a corresponding value in this case in order to validate the CSR.
Here we return an Address with an explicit empty trailing domain name iff we have DHCP Options Set with no `domain-name` key, which we add as a NodeInternalDNS (and Hostname) (without a trailing '.').
Note: Bug (and fix) reproduction and verification steps are …
> Bug 2072195: Custom DHCP Option Set: empty domain-name is a valid custom domain

- pkg/actuators/awsplacementgroup/controller.go
- pkg/actuators/awsplacementgroup/controller_test.go
- pkg/actuators/machine/actuator.go
- pkg/actuators/machine/actuator_test.go
- pkg/actuators/machine/controller_test.go
- pkg/actuators/machine/machine_scope.go
- pkg/actuators/machine/machine_scope_test.go
- pkg/actuators/machine/reconciler_test.go
- pkg/client/client.go
- pkg/client/mock/client_generated.go
When region cannot be validated locally from vendored aws/endpoints/defaults.go call AWS describeRegions API
to get list of regions and validate requested region with it.
This allows new AWS regions to work on older versions of OpenShift
without having to backport AWS SDK.
Requires https://github.com/openshift/machine-api-operator/pull/1007 to merge first
> [OCPCLOUD-1159] Validate unknown regions using AWS API

- go.mod
- go.sum
- vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
- vendor/modules.txt
It bumps machine-api-operator to the latest revision.
> Bump machine-api-operator to 25e61c2

- pkg/actuators/machine/instances.go
Now we check securityGroups parameter, which contains a list of SG filters. Instead, we shoud check the list of IDs that we get from the server.
> Bug 2060068: check securityGroupIDs for emptiness

- pkg/actuators/machine/reconciler.go
This is a bug fix for panic when deleting a machine and trying to access a value from its annotations while the map is not initialized.
> Bug 2106733: Fix panic when accessing nil machine annotations map

- pkg/actuators/machineset/controller.go
Use `Errorf` to get the `%s` and `%v` formatting, avoiding logs like:
Unable to set scale from zero annotations: unknown instance type: %sm6a.8xlarge
where the `Error` was treating the `%s` as a literal, and not as a format placeholder.
Generated wth:
```console
$ sed -i 's/klog.Error(\(.*%\)/klog.Errorf(\1/' $(git grep -l 'klog.Error(.*%')
```
> pkg/actuators/machineset/controller: Fix %s in scale-from-zero logging

- go.mod
- go.sum
- vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
- vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/drain_controller.go
- vendor/modules.txt
This bumps the MAO dependency to include the new changes for only draining a single control plane machine at once
XREF: openshift/machine-api-operator#1066
> Update Machine API Operator dependency

- pkg/actuators/machine/instances.go
- pkg/actuators/machine/reconciler.go
- pkg/actuators/machine/reconciler_test.go
This PR removes the full error from the Reason field in RegisterFailedInstanceXXXX metrics, because it was causing the metric to have high/unbound cardinality. The full error is still logged, so this PR should not affect the ability to troubleshoot issues.
> OCPBUGS-11223: Reduce metrics cardinality

- pkg/actuators/machine/actuator_test.go
- pkg/actuators/machine/controller_test.go
- pkg/actuators/machine/instances.go
- pkg/actuators/machine/reconciler_test.go
Right now if these 2 fields are mismatched, the machine gets to running with no issues. This fix proposes additional logic to determine whether the `subnetID` and `a.Zone` are the same value. If not, we log an message to the controller so the user can see it.
> OCPBUGS-6882: Log to user that the subnet id and zone fields are mismatched

- pkg/actuators/machineset/controller.go
Use the upstream annotation for the labels as the team is transitioning to use the upstream labels for all the other annotations too and making this in advance allow us not to support both the annotation for the labels cases.
cc @elmiko as discussed past week
> Fixes for the labels capacity annotation

- pkg/termination/handler_test.go
This change moves the bad url test to its own `Context` block so that it does not get caught in the mock termination service counter. In some cases it is possible for the bad url test to be run first, when this happens the counter will never advance because the url is not valid. This produces a dead lock condition in the test. Migrating the test to its own block alleviates this issue.
This change also updates the "not fulfilled" test to ensure that the counter is updated when the http handler is replaced.
> OCPBUGS-20266: update bad url endpoint termination handler test

- pkg/actuators/machine/actuator_test.go
- pkg/actuators/machine/controller_test.go
- pkg/actuators/machine/instances.go
- pkg/actuators/machine/instances_test.go
- pkg/actuators/machine/reconciler_test.go
- pkg/actuators/machine/stubs.go
This PR introduces support of Carrier IP Address assignment when `PublicIP` flag is set to `true` in the Machine Configuration.
When PublicIP is set in Machines which is set to launch in subnets with zone type `wavelength-zones`, the RunInstance must set the `AssociateCarrierIpAddress` in the network interface configuration.
This change is part of the full support of AWS Wavelength on OCP as part of 'edge nodes'. It is required only when launching instances in public subnets in Wavelength Zones.
Research: https://issues.redhat.com/browse/SPLAT-1045
Tracking card: https://issues.redhat.com/browse/SPLAT-1220
Installer full IPI support for Wavelength Zones: https://github.com/openshift/installer/pull/7369
Enhancement: https://github.com/openshift/enhancements/pull/1510
> SPLAT-1220: Assign Carrier IP to launch EC2 in AWS Wavelength Zones

- .snyk
this change is being added to pickup the vendor files that are appearing in the cachito expansion.
> OCPBUGS-28325: add an extra vendor exclude to snyk config

- .ci-operator.yaml
- Dockerfile.rhel
- go.mod
- pkg/actuators/machine/machine_scope_test.go
Extends #102 to attempt to fix the unit tests that were failing
> OCPBUGS-34255: Updating ose-machine-api-provider-aws-container image to be consistent with ART for 4.17

- pkg/actuators/machine/reconciler.go
- pkg/actuators/machine/reconciler_test.go
- pkg/actuators/machine/utils.go
This is a PR to add terminated as a handled state, so if AWS terminates instances before they are ready the instance should no longer get stuck. Creating it as a draft PR to get input/test my changes.
> OCPBUGS-15255: Add terminated as a handled state so terminated instances don't get stuck

- pkg/actuators/machine/instances.go
- pkg/actuators/machine/instances_test.go
This PR enforces the public IP assignment attribute* to be always set
when `publicIp` is set in the machine object. This behavior has been
changed in https://github.com/openshift/machine-api-provider-aws/pull/78 when the Wavelength zone support was added,
requiring an different attribute to assign public IP on launch
from a carrier infrastructure.
*attibute mutually exclusive required to assign public IP to an EC2
instance on launch by zone type:
- availability-zone: AssociatePublicIpAddress
- local-zone: AssociatePublicIpAddress
- wavelength-zone: AssociateCarrierIpAddress
> OCPBUGS-44373: fix Associate*IpAddress flag when launch EC2

- pkg/actuators/machine/instances.go
- pkg/actuators/machine/instances_test.go
This PR enforces the public IP assignment attribute* to be always set when `publicIp` is set in the machine object. This behavior has been changed in #78 when the Wavelength zone support was added, requiring an different attribute to assign public IP on launch from a carrier infrastructure.
*attibute mutually exclusive required to assign public IP to an EC2 instance on launch by zone type:
- availability-zone: AssociatePublicIpAddress
- local-zone: AssociatePublicIpAddress
- wavelength-zone: AssociateCarrierIpAddress
> [release-4.16] OCPBUGS-46508: fix Associate*IpAddress flag on launch EC2

- pkg/actuators/machine/instances.go
- pkg/actuators/machine/instances_test.go
If only MarketType=Spot is specified but spotMarketType is not provided, then we must explicitly add spotMarketType to the API config.
> [release-4.19] OCPBUGS-52454: Add spotMarketRequest on marketType spot

- cmd/manager/main.go
- pkg/actuators/machineset/controller.go
- pkg/actuators/machineset/controller_test.go
This was missed when https://github.com/openshift/machine-api-operator/pull/1287 was added.
The machineset annotation controller must respect the paused condition for a MachineSet.
Context: https://redhat-internal.slack.com/archives/GE2HQ9QP4/p1747830982876869
> OCPBUGS-56487: fix: make machineset annotation controller respect paused condition

- pkg/actuators/machineset/controller.go
- pkg/actuators/machineset/controller_test.go
Reconciliation can continue only if the authoritativeAPI is set to a value is set to MachineAPI.
This extra check is needed because in early stages of reconciliation of a new MAPI MachineSet the Paused condition might not yet be set, as such the authority status needs to be checked directly to ensure correct behaviour.
> OCPBUGS-57581: fix: machineset annotation controller: guard on status authoritativeAPI
